let pages=[];
const synonyms={retenes:['reten','retén','retenes','anillo obturador','anillos obturadores','obturador','radial'],horquilla:['horquilla','telescopica','telescópica','barra','barras','botella','botellas'],purgar:['purgar','purga','purgado','sangrar','sangrado','aire','purga de aire'],freno:['freno','frenos','pinza','líquido de frenos','liquido de frenos','disco'],aceite:['aceite','lubricante','motor oil','filtro de aceite'],valvulas:['válvula','válvulas','culata','juego de válvulas','reglaje'],pares:['par','pares de apriete','nm','torque','apretar'],rueda:['rueda','cojinete','rodamiento','llanta','neumático','eje'],suspension:['suspensión','amortiguador','amortiguadores','muelle','conjunto telescópico'],motor:['motor','cigüeñal','cilindro','culata','pistón','biela'],electricidad:['eléctrico','electricidad','batería','alternador','relé','conector','cableado'],combustible:['combustible','depósito','bomba','inyector','gasolina'],refrigeracion:['refrigeración','refrigerante','radiador','bomba de agua','termostato']};
const intent={'cambiar retenes de horquilla':['retenes','horquilla','desmontar','montar'],'purgar freno':['purgar','freno','purga','líquido'],'cambiar aceite motor':['aceite','motor','filtro','llenado'],'par pinza freno':['pinza','freno','nm'],'reglaje valvulas':['válvulas','culata','juego'],'cojinete rueda':['cojinete','rueda','rodamiento']};
const toolMap={
 '46 52 510':{name:'Bastidor/caballete especial para la rueda trasera',desc:'Para elevar y asegurar la motocicleta por el basculante cuando no se utiliza caballete central.'},
 '36 3 971':{name:'Caballete básico para rueda trasera',desc:'Base del bastidor especial de rueda trasera.'},
 '36 3 974':{name:'Soportes del bastidor de rueda trasera',desc:'Soportes regulables que se apoyan en el basculante.'},
 '46 5 721':{name:'Gancho para muelles',desc:'Herramienta para desmontar y montar los muelles tensores del caballete lateral.'},
 '46 5 741':{name:'Unidad básica para muelles del caballete central',desc:'Útil para pretensar los muelles del caballete central.'},
 '46 5 746':{name:'Soporte/gancho para muelles del caballete central',desc:'Accesorio que trabaja con la unidad básica para colocar los muelles.'},
 '12 3 621':{name:'Extractor de bobinas de encendido',desc:'Útil para extraer las bobinas de encendido directo.'},
 '12 1 220':{name:'Llave para bujías',desc:'Llave especial para desmontar y montar las bujías.'},
 '21 4 606':{name:'Extractor de bloqueo del embrague',desc:'Útil especial para retirar el bloqueo indicado en el procedimiento del embrague.'},
 '31 42 511':{name:'Útil de apoyo/elevación del conjunto delantero',desc:'Herramienta utilizada en los trabajos del cabezal de dirección.'},
 '31 42 514':{name:'Útil para ajuste del cojinete de dirección',desc:'Herramienta especial para ajustar el cojinete del cabezal del manillar.'},
 '31 42 527':{name:'Útil de desmontaje/montaje del puente de horquilla',desc:'Herramienta asociada al trabajo del puente inferior de la horquilla.'},
 '31 42 528':{name:'Útil para puente superior de horquilla',desc:'Herramienta especial asociada al desmontaje/montaje del puente superior.'}
};
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s.]/g,' ').replace(/\s+/g,' ').trim()}
const rev={}; for(const [k,a] of Object.entries(synonyms)){rev[norm(k)]=k; a.forEach(x=>rev[norm(x)]=k)}
function terms(q){const n=norm(q),out=new Set(n.split(' ').filter(x=>x.length>1));for(const t of [...out])if(rev[t]){out.add(rev[t]);synonyms[rev[t]].forEach(x=>out.add(norm(x)))}for(const[k,v]of Object.entries(intent))if(norm(q).includes(norm(k)))v.forEach(x=>out.add(norm(x)));return[...out]}
function score(text,q){const n=norm(text),nq=norm(q);if(!nq)return 0;let s=0;if(n.includes(nq))s+=40;for(const t of terms(q))if(n.includes(t))s+=t.length>=5?4:2;const words=norm(q).split(' ').filter(x=>x.length>2),hits=words.filter(w=>n.includes(w)).length;if(words.length&&hits===words.length)s+=25;return s}
function category(text){const n=norm(text);let best='general',bs=0;for(const[c,a]of Object.entries(synonyms)){const z=a.reduce((v,x)=>v+(n.includes(norm(x))?1:0),0);if(z>bs){bs=z;best=c}}return best}
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]))}
function snippet(text,q){const qs=terms(q).filter(x=>x.length>2),n=norm(text);let pos=Infinity;for(const t of qs){const p=n.indexOf(t);if(p>=0)pos=Math.min(pos,p)}if(!isFinite(pos))pos=0;let a=Math.max(0,pos-180),b=Math.min(text.length,a+620),raw=text.slice(a,b),safe=esc(raw);for(const t of qs.slice(0,12)){const re=new RegExp('('+t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','ig');safe=safe.replace(re,'<mark>$1</mark>')}return(a?'…':'')+safe+(b<text.length?'…':'')}
function extractTorque(text){const out=[],re=/([^.!?\n]{0,100}\b(?:\d{1,3}(?:[.,]\d+)?\s*Nm)\b[^.!?\n]{0,100})/gi;let m;while((m=re.exec(text))&&out.length<8)out.push(m[1].trim());return[...new Set(out)]}
function extractTools(text){const found=[];const re=/(?:N\.º|No\.?|Nº)\s*([0-9]{1,2}\s+[0-9]{1,2}\s+[0-9]{1,3})/gi;let m;while((m=re.exec(text))){const code=m[1].trim();if(!found.some(x=>x.code===code))found.push({code,...(toolMap[code]||{name:'Herramienta especial BMW',desc:'Consulta el procedimiento original para identificar el útil exacto.'})})}return found.slice(0,10)}
function toolCards(tools){if(!tools.length)return '<p>No se ha identificado una herramienta especial por código en este fragmento.</p>';return tools.map(t=>`<div class="tool"><div class="toolIcon">🔧</div><div><b>${esc(t.name)}</b><div class="toolDesc">${esc(t.desc)}</div><span class="toolCode">BMW ${esc(t.code)}</span></div></div>`).join('')}
function makeWorkCard(p,q){const torques=extractTorque(p.text),tools=extractTools(p.text),hasWarn=/ATENCIÓN|PELIGRO|ADVERTENCIA|PRECAUCIÓN/i.test(p.text);return `<div class="work"><div class="workHead"><span>FICHA DE TALLER</span><b>Página ${p.page}</b></div><h2>${esc(q)}</h2><div class="grid"><div><h3>🛠️ Procedimiento</h3><p>${snippet(p.text,q)}</p></div><div><h3>🔩 Pares de apriete</h3>${torques.length?'<ul>'+torques.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>':'<p>No detectados en este fragmento.</p>'}</div><div><h3>🔧 Herramientas especiales</h3>${toolCards(tools)}</div><div><h3>⚠️ Seguridad</h3><p>${hasWarn?'El procedimiento contiene advertencias. Lee siempre el original completo antes de intervenir.':'No se ha detectado una advertencia en este fragmento.'}</p></div></div><div class="actions"><button class="primary" onclick="openOriginal(${p.page})">📖 Abrir manual original completo</button><button class="secondary" onclick="openPage(${p.page})">📄 Ver página del procedimiento</button></div></div>`}
function render(q){q=q.trim();const cat=document.getElementById('cat').value;if(!q){document.getElementById('status').textContent='Escribe una búsqueda o elige una tarea.';document.getElementById('results').innerHTML='';return}const res=pages.map(p=>({p,s:score(p.text,q)})).filter(x=>x.s>0&&(!cat||category(x.p.text)===cat)).sort((a,b)=>b.s-a.s).slice(0,50);document.getElementById('status').textContent=`${res.length} resultados para “${q}”`;document.getElementById('results').innerHTML=res.map(x=>`<article class="card" onclick="showWork(${x.p.page},'${esc(q).replace(/'/g,'&#39;')}')"><div class="title">Página ${x.p.page} · ${esc(category(x.p.text))}</div><div class="meta">Relevancia ${x.s} · ${esc(x.p.chunk)}</div><div class="snippet">${snippet(x.p.text,q)}</div><div class="open">Abrir ficha de taller →</div></article>`).join('')||'<div class="card">No he encontrado coincidencias. Prueba “retenes horquilla”, “purgar freno”, “aceite motor”, “válvulas” o “par pinza”.</div>'}
function showWork(page,q){const p=pages[page-1];document.getElementById('viewer').innerHTML=makeWorkCard(p,q)+`<div class="viewer"><iframe title="Manual BMW F 850 GS página ${page}" src="manual/${p.chunk}#page=${p.localPage}"></iframe></div>`;document.getElementById('viewer').scrollIntoView({behavior:'smooth',block:'start'})}
function openOriginal(page){const p=pages[page-1];window.open(`manual/${p.chunk}`,'_blank','noopener');}
function openPage(page){const p=pages[page-1];document.getElementById('viewer').innerHTML=`<div class="viewer"><iframe title="Manual BMW F 850 GS página ${page}" src="manual/${p.chunk}#page=${p.localPage}"></iframe></div>`;document.getElementById('viewer').scrollIntoView({behavior:'smooth',block:'start'})}
function goHome(){window.scrollTo({top:0,behavior:'smooth'});const q=document.getElementById('q');q.value='';document.getElementById('cat').value='';document.getElementById('results').innerHTML='';document.getElementById('viewer').innerHTML='<div class="empty">Selecciona un resultado para ver su ficha de taller y el manual original.</div>';document.getElementById('status').textContent='Manual listo · 974 páginas indexadas.'}
async function init(){try{const r=await fetch('data/index.json');pages=await r.json();document.getElementById('status').textContent=`Manual cargado · ${pages.length} páginas indexadas.`}catch(e){document.getElementById('status').textContent='No se ha podido cargar el índice. Comprueba que data/index.json está en GitHub.';return}const qEl=document.getElementById('q');document.getElementById('go').onclick=()=>render(qEl.value);qEl.addEventListener('keydown',e=>{if(e.key==='Enter')render(qEl.value)});document.getElementById('cat').onchange=()=>render(qEl.value);document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{qEl.value=b.dataset.q;render(qEl.value)});document.getElementById('about').onclick=()=>document.getElementById('dlg').showModal();document.getElementById('home').onclick=goHome;document.getElementById('topHome').onclick=goHome}
init();
